version: '3.9'

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: "INFO"

volumes:
  qdrant_data:


#services:
#  pgvector:
#    image: 'pgvector/pgvector:pg16'
#    environment:
#      - 'POSTGRES_DB=cv-theque-store'
#      - 'POSTGRES_PASSWORD=password'
#      - 'POSTGRES_USER=admin'
#    labels:
#      - "org.springframework.boot.service-connection=postgres"
#    ports:
#      - '5432:5432'
